### PR TITLE
only enable waitress IPv6 support if we should serve on AF_INET6

### PR DESCRIPTION
**Pull request by evgeni**
Closes: #82

### CODE REVIEW

**Comment by evgeni** [comment]
I don't understand why `coverage combine` fails. :(

**Comment by tarekziade** [comment]
Looks good, thanks. What is the failure with 'combine' ?

**Comment by evgeni** [comment]
Travis would error with

```
py27 runtests: commands[2] | coverage combine
No data to combine
ERROR: InvocationError: '/home/travis/build/circus-tent/chaussette/.tox/py27/bin/coverage combine'
```

see https://travis-ci.org/circus-tent/chaussette/builds/212651180

**Comment by tarekziade** [comment]
Ah ok I see. You can prefix it with "- " it should ignore that warning. I'll merge the PR then, thanks!

**Comment by evgeni** [comment]
meh, I don't know why travis now blows up completelly.

**Comment by tarekziade** [comment]
ok no worries, I'll take it from here thanks for the PR!

**Comment by evgeni** [comment]
thanks!

**Pull request merged**
